version: '3.6'
services: 
  pgadmin-compose:
      image: dpage/pgadmin4
      environment: 
          PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
          PGADMIN_DEFAULT_PASSWORD: "test123!"
      ports: 
          - "16543:80"  

networks: 
  default: 
    external: 
      name: local_network_1